# Generated by Django 2.2.1 on 2019-05-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('C', 'Customer'), ('F', 'Front'), ('A', 'AirCManager'), ('H', 'HotelManager')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('temp', models.IntegerField()),
                ('wind', models.CharField(choices=[('L', 'Low'), ('M', 'Middle'), ('H', 'High')], max_length=5)),
                ('price', models.FloatField()),
                ('room_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='温控系统.AirC')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='温控系统.User')),
            ],
        ),
    ]
