# Generated by Django 2.2.1 on 2019-06-02 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('温控系统', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='温控系统.AirC')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='温控系统.User')),
            ],
        ),
    ]
