# Generated by Django 2.2.1 on 2019-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('温控系统', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userecord',
            name='room_num',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userecord',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='room',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userroom',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
