# Generated by Django 2.2.1 on 2019-06-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('温控系统', '0002_userroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='reachtimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userroom',
            name='schedulingtimes',
            field=models.IntegerField(default=0),
        ),
    ]
